# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
  - planet4.local

paths:
  base: ..
  content: content
  wp: wordpress

# Should we use multisite?
multisite: No

# Set database values to save the prefix so Chassis doesn't freak out on
# re-provisions after tests.
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_

# Extensions
#
# Install a list of extensions automatically
extensions:
  - paulgibbs/composer
  - chassis/tester
  - chassis/xdebug
  - chassis/memcache

php: 7.2

virtualbox:
  memory: 2048
